service: laravel-bref

provider:
  name: aws
  region: eu-north-1
  stage: ${opt:stage, 'dev'} # defaults to dev, can be overridden with --stage <stage> on the commandline
  runtime: provided
  environment:
    APP_ENV: production
    APP_KEY: "base64:+iTro5CgvnG6vFjPo06vGEpyBZHIezyuTfVcU/LDN7c="
    APP_STORAGE: /tmp
    # Log to stderr to get CloudWatch Logs to pick it up
    LOG_CHANNEL: stderr
    # Dont store sessions
    SESSION_DRIVER: array
    VIEW_COMPILED_PATH: /tmp/storage/framework/views

plugins:
  - ./vendor/bref/bref

package:
  excludeDevDependencies: false
  exclude:
    - ./**
  include:
    - app/**
    - bootstrap/**
    - config/**
    - database/**
    - public/index.php
    - resources/lang/**
    - resources/views/**
    - routes/**
    - vendor/**
    - artisan

functions:
  website:
    handler: public/index.php
    description: ''
    memorySize: 2048
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      # Using HTTP API
      - httpApi: '*'
