service: laravel-bref

provider:
  name: aws
  region: eu-north-1
  runtime: provided
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
      Resource:
        - !GetAtt cacheTable.Arn
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
      Resource:
        - !GetAtt queue.Arn
  environment:
    APP_ENV: production
    APP_KEY: "base64:+iTro5CgvnG6vFjPo06vGEpyBZHIezyuTfVcU/LDN7c="
    APP_STORAGE: /tmp
    CACHE_DRIVER: dynamodb
    SESSION_DRIVER: dynamodb
    SESSION_STORE: dynamodb
    DYNAMODB_CACHE_TABLE: laravel_bref_cache
    LOG_CHANNEL: stderr
    VIEW_COMPILED_PATH: /tmp/storage/framework/views
    ASSET_URL: !Join
      - ''
      - - 'https://'
        - !GetAtt CDN.DomainName
    QUEUE_CONNECTION: sqs
    SQS_QUEUE: https://sqs.eu-north-1.amazonaws.com/148530641072/laravel_bref_queue
    SQS_PREFIX: https://sqs.eu-north-1.amazonaws.com/148530641072

plugins:
  - ./vendor/bref/bref

package:
  exclude:
    - .env
    - tests/**
    - node_modules/**
    - storage/**

functions:
  website:
    handler: public/index.php
    description: 'Laravel website'
    memorySize: 2048
    timeout: 10 # in seconds (API Gateway has a timeout of 30 seconds)
    reservedConcurrency: 10 # limit to 10 concurrent executions
    layers:
      - ${bref:layer.php-73-fpm}
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'

  artisan:
    handler: artisan
    description: 'Artisan console'
    layers:
      - ${bref:layer.php-73} # PHP
      - ${bref:layer.console} # The "console" layer
    events:
      - schedule:
          description: Running the Laravel Scheduler (schedule:run) each minute
          rate: rate(1 minute)
          input:
            cli: schedule:run

  queue:
    handler: queue-handler.php
    description: 'Laravel Queue handler for SQS'
    layers:
      - ${bref:layer.php-73}
    events:
      - sqs:
          arn: !GetAtt queue.Arn
          batchSize: 1

resources:
  Resources:
    assetBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "wb-laravel-bref-assets"
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html

    cacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: laravel_bref_cache
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH

    queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: laravel_bref_queue
        ReceiveMessageWaitTimeSeconds: 20

    Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: wb-laravel-bref-assets-${self:provider.stage}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html

    CDN:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          PriceClass: PriceClass_100
          HttpVersion: http2
          Origins:
            - Id: Assets
              DomainName: !GetAtt Assets.DomainName
              CustomOriginConfig:
                OriginProtocolPolicy: 'http-only' # S3 websites only support HTTP
          DefaultCacheBehavior:
            AllowedMethods: [GET, HEAD]
            TargetOriginId: Assets
            #DefaultTTL: 0
            #MinTTL: 0
            #MaxTTL: 0
            # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-forwardedvalues.html
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none # Forward cookies to use them in PHP
            ViewerProtocolPolicy: redirect-to-https
          CustomErrorResponses:
            # Do not cache HTTP errors
            - ErrorCode: 500
              ErrorCachingMinTTL: 0
            - ErrorCode: 504
              ErrorCachingMinTTL: 0

  Outputs:
    queueUrl:
      Value: !Ref queue
