service: laravel-bref

provider:
  name: aws
  region: eu-north-1
  runtime: provided
  environment:
    APP_ENV: production
    APP_KEY: "base64:+iTro5CgvnG6vFjPo06vGEpyBZHIezyuTfVcU/LDN7c="
    APP_STORAGE: /tmp
    SESSION_DRIVER: array
    VIEW_COMPILED_PATH: /tmp/storage/framework/views
    ASSET_URL: https://wb-laravel-bref-assets.s3.eu-north-1.amazonaws.com

plugins:
  - ./vendor/bref/bref

package:
  exclude:
    - tests/**
    - node_modules/**
    - storage/**

functions:
  website:
    handler: public/index.php
    description: 'Laravel website'
    memorySize: 2048
    timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
    layers:
      - ${bref:layer.php-73-fpm}
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'

resources:
  Resources:
    assetBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "wb-laravel-bref-assets"
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
